### ISSUE TITLE
Training on experiment logigng 

### ISSUE THREAD

**Issue by Croydon-Brixton** [ai4er-cdt/resources#15]
I've worked a bit with "Sacred" before and could do a tutorial on that, but don't know the other solutions in the space (e.g. neptune) which might be even better. 

@KenzaxTazi You seem to be quite knowledgable about that, would you be comfortable collaborating to create a training for that with me or do you know someone who could?

**Comment by herbiebradley** [comment]
I have used [Weights and Biases](https://www.wandb.com/) (which I believe is similar to Neptune) a lot in my masters so I can put a tutorial for that on the wiki.

**Comment by herbiebradley** [comment]
Also ongoing effort in code review group - W&B's tutorial will do a better job than I could anyway and there's a link on the wiki.
