### ISSUE TITLE
Distributed  Computing

### ISSUE THREAD

**Issue by Ira-Shokar** [ai4er-cdt/resources#2]
Request:

Upload resources on how to get started with understanding distributed computing.

**Comment by sdat2** [comment]
Charles Simpson made a great video introduction to Dask for BAS, so hopefully we could share that on this webpage.

**Comment by C-H-Simpson** [comment]
@sdat2 do you mean the one on xarray? 
The recording is on the BAS digital workspace; I don't have the file, or the file permissions to share it outside BAS. @scotthosking do you know who has the original recording?

**Comment by scotthosking** [comment]
Hi @C-H-Simpson , I should be able to find it but for now a link to a YouTube video (Dask + Xarray) would be the most straight forward thing to do as we can add it to a wiki page. This looks like a good one to start with: https://www.youtube.com/watch?v=nnndxbr_Xq4
@herbiebradley , could you add this to a Python section of the wiki?
