### ISSUE TITLE
Replacing CEDSG acronym...

### ISSUE THREAD

**Issue by scotthosking** [ai4er-cdt/resources#26]
I'd like to consider replacing the CEDSG acroynm as it doesn't roll-off-the-tongue and the group itself is largely indistinguishable from the AI4ER CDT (+ affilated students) group.

I'd like to suggest the AI4ER Student committee put forward some suggestions to the AI4ER CDT Management Board.

e.g., why not just go with the 'AI4ER Community'

**Comment by ata27** [comment]
I agree that CEDSG doesn't role of the tongue but neither does CCfCS. If we can find a different acronym that's good but I'd seriously avoid anything based around "AI4ER blah". You want the Centre to be distinct from the CDT as is the case with CCfCS and C-CLEAR and all other CDTs and DTPs and the associated Centres. Centres should be the inclusive home for all research activities in a theme/area, where as CDTs and DTPs have a very specific remit around the students which they support. That's my thoughts anyway.

**Comment by scotthosking** [comment]
Thanks Alex, that is useful and I do agree - my issue was not well thought-out and rather brash. I still think the acronym/name could be improved but we should put a wider Centre structure in place within which the CDT sits. We should discuss this at the Management level etc -
