### ISSUE TITLE
Intro to clean coding practices

### ISSUE THREAD

**Issue by Croydon-Brixton** [ai4er-cdt/resources#3]
Content:
-  Submitting clean code with linting
-  Using code formatting
-  Disucssing smart design principles for repos/reporducibility & later deployment
-  Useful general project setup

Due:
Mid October

**Comment by scotthosking** [comment]
The code review group might be good for this, cc @RachelFurner and @michellewl

**Comment by Croydon-Brixton** [comment]
Ongoing effort in code review group.
