### ISSUE TITLE
Working on GPUs/using CUDA

### ISSUE THREAD

**Issue by shmh40** [ai4er-cdt/resources#7]
Maybe one for a bit further down the line, but if anyone has experience using CUDA/GPUs some pointers would be good!

**Comment by hmceoadxat** [comment]
Not an expert, but happy to share my experience using PyTorch on an Nvidia GPU. Questions welcome.

**Comment by Croydon-Brixton** [comment]
Happy to help out as well! (:

**Comment by herbiebradley** [comment]
Me too - I have done a lot of cloud GPU renting with both PyTorch and Tensorflow. :D

**Comment by herbiebradley** [comment]
The wiki links to resources for this like the Pytorch tutorials - questions can be asked in the Slack.
