### ISSUE TITLE
Overview of key environmental data sources

### ISSUE THREAD

**Issue by Croydon-Brixton** [ai4er-cdt/resources#8]
Create an overview page for key data sources for environmental science data with a short description of what data it gives + link to the data source + (optional: metainformation on resolution/update frequency/ ...)

**Comment by scotthosking** [comment]
I've forked this repo which has lots of data and information: https://github.com/ai4er-cdt/Environmental_Intelligence

@rockita (a Turing colleague) put this great resource together
